### ISSUE TITLE
Pack error & Build empty

### ISSUE THREAD

**Issue by jt-wang** [SimulatedGREG/electron-vue#201] opened 2017-04-30 05:01 UTC
##### Describe the issue / bug.
I came across two major problems when I tried to pack and build the app written with electron-vue.
1. Like #174 , during the packing process, 
```
ERROR in renderer.js from UglifyJs
Unexpected token: name (warn) [renderer.js:29054,4]
```
I tried several solutions mentioned in other issues but none of them worked, and only the workaround in #174 by @deboyblog succeeded. I think my error has something to do with "lodash", which is the only dependency that I installed as a universal library and uses the "_" as the variable name. Anyway, only by removing the corresponding configuration in `webpack.renderer.config.js
` can I make it to pack.

2. Like #200 , the built app is totally empty. Following the instruction in #200 does solve the problem.

##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version: 7.7.3
  * NPM version: 4.1.2
  * vue-cli version: (if necessary) 2.8.1
  * Operating System: macOS 10.12.4

#### *If you are looking to suggest an enhancement or feature, then feel free to remove everything above.*

Many thanks for your project, and it does help me a lot in building a cross-platform app. I hope that someone can join in looking into the problems above, since they are quite significant for an ultimate outcome (packing and building), or at least there is a link in the README referring to the workarounds.

**Comment by NMonst4** [comment] 2017-05-01 11:43
did you try this https://github.com/SimulatedGREG/electron-vue/issues/200

**Comment by SimulatedGREG** [comment] 2017-05-06 07:47
Fix has been pushed the `dev` branch. Check #171 for more info on final release.

**Closed by SimulatedGREG** 2017-05-06 07:47 UTC

**Comment by Sndan** [comment] 2017-06-03 10:43
Hello ,

I have same problem.
I tried with the solution here #200 
and here https://github.com/SimulatedGREG/electron-vue/commit/abe2e84f3174ea295f58addd4a2e666857f93867

but still the problem is on and the build result is the old blank App 


thx,,

**Comment by AlexQuidditch** [comment] 2017-07-11 15:45
+1

I tried to init template and build it immediatly:

``$ vue init simulatedgreg/electron-vue el-test``
``$ cd el-test``
``& yarn && yarn run build:win32``

and I have result is blank app window

Versions:
Microsoft Windows: 10.0.15063
vue-cli: 2.8.2
npm: 5.2.0
node: 7.10.0
