### ISSUE TITLE
 Vue packages version mismatch

### ISSUE THREAD

**Issue by wpf1994** [SimulatedGREG/electron-vue#81] opened 2016-12-12 03:46 UTC
hi, I use vue-cli product my project, I already npm install,it's successful, then, I npm run dev, It's wrong,  it's shown below.
![image](https://cloud.githubusercontent.com/assets/10007650/21087332/cc49eab0-c05f-11e6-8bdf-24b8ee6f9a2a.png)

Also,I chose vue 2.X in vue init, please give me a suggestion, thank you very much

  * Node version: v5.7.1
  * NPM version: 3.6.0
  * Operating System: OS X 10.11.6

**Comment by SimulatedGREG** [comment] 2016-12-12 04:18
@wpf1994 

I am unable to reproduce this issue. You stated that you have chosen `vue@^2` during scaffolding, but the error shows `vue@1.0.26` is installed. Did you manually change something? Because scaffolding for both v1 and v2 doesn't produce any errors for me.

**Comment by wpf1994** [comment] 2016-12-12 04:54
@SimulatedGREG 

I am not to manually anything,  I just `npm` install use https://registry.npm.taobao.org of source,  The content that scaffolding product `package.json` generates is shown below, I just unknown chosen `vue@^2` , but error about `vue@1.0.26`,  I guess the reason of scaffolding product `package.json` version, or `npm` source? 

### `app/package.json`
![image](https://cloud.githubusercontent.com/assets/10007650/21088397/9afdc3c8-c069-11e6-850e-046abf23d26c.png)


### `/package.json`
![image](https://cloud.githubusercontent.com/assets/10007650/21088408/bf892afc-c069-11e6-8a12-27e29180ba47.png)
![image](https://cloud.githubusercontent.com/assets/10007650/21088409/c93c1fe6-c069-11e6-99e7-df647d7b42fc.png)

**Comment by SimulatedGREG** [comment] 2016-12-12 05:06
I would believe this would be an issue with https://registry.npm.taobao.org, as both me and the CI server are not having issues. I visited https://npm.taobao.org/package/vue and saw that the versions seem to be out of date with the official npm registry.

![image](https://cloud.githubusercontent.com/assets/8327811/21088604/42a3a4c2-bff6-11e6-9880-5cb3d142e854.png)

**Comment by wpf1994** [comment] 2016-12-12 06:56
@SimulatedGREG 
I use npm offfical source, result is `npm WARN error-test@0.0.0 No repository field.`, the error is the same as before。I tried again and again

## npm source
![image](https://cloud.githubusercontent.com/assets/10007650/21090482/0fb9005e-c07b-11e6-89cd-67f93a5ad41a.png)

## my operation is below
![image](https://cloud.githubusercontent.com/assets/10007650/21090274/8ff4bc74-c079-11e6-84b8-6ecfb4b9481b.png)

**Comment by AkiraLaine** [comment] 2016-12-12 07:01
@wpf1994 - Well, it looks like by using the official npm source, everything works.

The `NPM Warn` error is nothing to worry about.

**Comment by wpf1994** [comment] 2016-12-12 07:07
@AkiraLaine  but implement `npm run dev`, It's the wrong question, as I mentioned in the beginning，and open electron , view is below
![image](https://cloud.githubusercontent.com/assets/10007650/21090739/af37a120-c07c-11e6-81d4-a8d9f6f29a06.png)

**Comment by SimulatedGREG** [comment] 2016-12-12 07:11
Please take a look at [this FAQ](https://simulatedgreg.gitbooks.io/electron-vue/content/docs/faqs.html#why-does-my-electron-app-show-a-file-explorer) for more information about the blank app as your first screenshot showed that `app/src/routes.js` had one error.

**Comment by wpf1994** [comment] 2016-12-12 07:56
I'm so sorry, forgot to say, if chose `vue@^1.x`, it's successful, also the failure of chose `vue@^2.x` ,I continue to look the reason of `vue@^2.x`

**Comment by lmiller1990** [comment] 2016-12-25 03:42
Hi, I also had this problem. I just followed the instructions on the readme and got the mismatch. I was able to resolve by following the errors webpack gave me (`npm install vue-loader vue`) which updated everything to the latest versions, and it's working fine now.

**Comment by SimulatedGREG** [comment] 2017-01-13 09:05
I believe this might have been a larger issue a recent release of `vue` and `vue-loader`, specially detailed [here](https://github.com/vuejs/vue/releases/tag/v2.1.7). I'm going to make a large release in the next few days so stayed tuned. Going to close this for now, feel free to comment back anything.

**Closed by SimulatedGREG** 2017-01-13 09:05 UTC
Labels: needs-repro

**Comment by lilien1010** [comment] 2017-03-25 13:19
I have been using the lastest vue,but why it keep shoing that I am using vue@2.1.8
![image](https://cloud.githubusercontent.com/assets/3814966/24322508/78a6a9d8-11a0-11e7-9fd6-5e0ffb772aec.png)

![image](https://cloud.githubusercontent.com/assets/3814966/24322518/9e42354a-11a0-11e7-99bb-5c51b3b32f8d.png)
