### ISSUE TITLE
npm run build  error

### ISSUE THREAD

**Issue by ibullet-chzn** [SimulatedGREG/electron-vue#295] opened 2017-06-30 03:45 UTC
Error: ENOENT: no such file or directory, stat '/Users/administrator/Documents/Electron/vue/project/node_modules/.npminstall/zip-stream/1.2.0/core-util-is/1.0.2/core-util-is'

**Comment by SimulatedGREG** [comment] 2017-06-30 20:13
@ibullet-chzn 

If you are using `electron-builder`, make sure to give that an update as a dependency of it was having issues.

```bash
yarn add -D electron-builder@^19

// or with npm

npm install --save-dev electron-builder@^19
```

**Comment by sugerPocket** [comment] 2017-07-01 02:08
@SimulatedGREG 
I have the same problem, this script `npm run build:linux` build successfully, but packager make the following ERROR

![image](https://user-images.githubusercontent.com/15670631/27758373-eedd85a4-5e44-11e7-940d-ea2d984e3f1a.png)

use `node v7.10.0`

**Comment by SimulatedGREG** [comment] 2017-07-01 02:21
Not entirely what the issue is here, as it more pertains to `electron-packager`. This issue is probably better suited for that community, but I would recommend trying to delete `app/node_modules` and reinstalling everything, and possibly trying [`yarn`](https://yarnpkg.org).

**Comment by sugerPocket** [comment] 2017-07-01 03:47
@SimulatedGREG 

I got it using `yarn`. I still don't know what make packager not work with `npm v4.2.0`.

Thx!

**Comment by SimulatedGREG** [comment] 2017-07-01 22:07
Yeah, `npm` runs into a few issues here and there when it comes to packaging in `electron`. `yarn` on the other hand has been proven to resolve many of those issues, and it also recommended by members of the @electron-userland, including the author of `electron-builder`.

Going to close this. Feel free to comment back any other issues.

**Closed by SimulatedGREG** 2017-07-01 22:07 UTC
Labels: needs-info

**Comment by ibullet-chzn** [comment] 2017-07-04 10:40
@SimulatedGREG 
i update electron-builder@^19 ,but my problems still exist

Error: ENOENT: no such file or directory, stat '/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/zip-stream/1.2.0/core-util-is/1.0.2/core-util-is'

**Comment by ibullet-chzn** [comment] 2017-07-04 10:43
take it away `electron-builder`

electron-builder 19.13.0
No native production dependencies
Packaging for darwin x64 using electron 1.7.4 to build/mac
Error: ENOENT: no such file or directory, stat '/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/zip-stream/1.2.0/core-util-is/1.0.2/core-util-is'
    at Error (native)
From previous event:
    at /Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/src/util/asarUtil.ts:94:13
From previous event:
    at /Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/src/util/asarUtil.ts:88:10
    at /Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder-util/19.12.0/electron-builder-util/src/fs.ts:62:60
    at /Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/graceful-fs/4.1.11/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at /Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder-util/19.12.0/electron-builder-util/src/fs.ts:57:10
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at /Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder-util/19.12.0/electron-builder-util/src/fs.ts:54:51
    at next (native)
    at go$readdir$cb (/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/graceful-fs/4.1.11/graceful-fs/graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at walk (/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder-util/19.12.0/electron-builder-util/out/fs.js:103:22)
    at /Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/src/util/asarUtil.ts:68:17
    at next (native)
From previous event:
    at AsarPackager.pack (/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/out/util/asarUtil.js:187:11)
    at /Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/src/platformPackager.ts:194:150
    at next (native)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at MacPackager.doPack (/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/out/platformPackager.js:260:11)
    at /Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/src/macPackager.ts:92:71
    at next (native)
From previous event:
    at MacPackager.pack (/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/out/macPackager.js:190:11)
    at /Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/src/packager.ts:230:24
From previous event:
    at Packager.doBuild (/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/out/packager.js:303:11)
    at /Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/src/packager.ts:161:52
    at next (native)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/out/packager.js:222:11)
    at /Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/src/builder.ts:256:40
    at next (native)
From previous event:
    at build (/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/src/cli/cli.ts:41:4)
    at Object.self.runCommand (/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/yargs/8.0.2/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/yargs/8.0.2/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/yargs/8.0.2/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/administrator/Documents/Electron/qianbaovue/project/node_modules/.npminstall/electron-builder/19.13.0/electron-builder/src/cli/cli.ts:36:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
