### ISSUE TITLE
vue-devtools?

### ISSUE THREAD

**Issue by rdpascua** [SimulatedGREG/electron-vue#16] opened 2016-08-12 14:57 UTC
I don't see any vue-devtools in my machine? Am I doing something wrong? 

![screenshot from 2016-08-12 22-57-15](https://cloud.githubusercontent.com/assets/2498246/17626521/243a535c-60e0-11e6-9fa1-6cca224cc1ac.png)

**Comment by SimulatedGREG** [comment] 2016-08-12 15:01
You might need to close and reopen the Dev tools. Check here for more info [https://simulatedgreg.gitbooks.io/electron-vue/content/docs/faqs.html](https://simulatedgreg.gitbooks.io/electron-vue/content/docs/faqs.html).

**Comment by rdpascua** [comment] 2016-08-12 15:43
Oh I see, I have the Vue tab now. Will try tinkering with this template

**Comment by wdmtech** [comment] 2016-10-06 11:45
Sorry to reopen - I'm not seeing the Vue tab even after several attempts at running/opening closing devtools 

![image](https://cloud.githubusercontent.com/assets/7282262/19151100/c1fe502c-8bc2-11e6-97d0-6752fd549907.png)

**Comment by SimulatedGREG** [comment] 2016-10-06 16:21
@wdmtech Did you see any console message about the dev tools not being installed properly? (Or even a success message?)

**Comment by wdmtech** [comment] 2016-10-06 16:25
Nothing unfortunately - just what's in that screenshot

**Comment by SimulatedGREG** [comment] 2016-10-06 16:32
@wdmtech Yes I see the screenshot, but I mean the terminal where you run `npm run dev`. lol

**Comment by wdmtech** [comment] 2016-10-06 16:39
Sorry haha, here you go!

**Comment by wdmtech** [comment] 2016-10-06 16:40
```bash

D:\Dev\vue-electron (master) (electron-quick-start@1.0.0) 06/10/2016 17:37:45.03
λ npm run dev
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\laragon2\\bin\\nodejs\\node.exe" "C:\\laragon2\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! missing script: dev
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Dev\vue-electron\npm-debug.log

D:\Dev\vue-electron (master) (electron-quick-start@1.0.0) 06/10/2016 17:37:55.44
λ cd ..\vue-electron\

D:\Dev\vue-electron (develop) (vue-electron@0.0.0) 06/10/2016 17:38:03.50
λ npm run dev

> vue-electron@0.0.0 dev D:\Dev\vue-electron
> node tasks/runner.js

Starting webpack-dev-server...

webpack  http://localhost:9080/

webpack  webpack result is served from /
content is served from D:\Dev\vue-electron\app\dist

webpack  Hash: aa4bdd9b33912abcc870
Version: webpack 1.13.2
Time: 4397ms
Asset       Size  Chunks             Chunk Names
build.js    2.34 MB       0  [emitted]  build
index.html  279 bytes          [emitted]
chunk    {0} build.js (build) 820 kB [rendered]
[0] multi build 52 bytes {0} [built]
[1] (webpack)-dev-server/client?http://localhost:9080 3.97 kB {0} [built]
[3] ./~/strip-ansi/index.js 161 bytes {0} [built]
[4] ./~/ansi-regex/index.js 135 bytes {0} [built]
[5] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
[6] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
[7] ./~/sockjs-client/lib/transport-list.js 613 bytes {0} [built]
[8] ./~/sockjs-client/lib/transport/websocket.js 2.71 kB {0} [built]
[9] ./~/sockjs-client/lib/utils/event.js 2 kB {0} [built]
[10] ./~/sockjs-client/lib/utils/random.js 746 bytes {0} [built]
[12] ./~/sockjs-client/lib/utils/url.js 975 bytes {0} [built]
[13] ./~/url-parse/index.js 9.91 kB {0} [built]
[14] ./~/requires-port/index.js 753 bytes {0} [built]
[15] ./~/url-parse/lolcation.js 1.58 kB {0} [built]
[16] ./~/querystringify/index.js 1.3 kB {0} [built]
[17] ./~/debug/node.js 4.76 kB {0} [built]
[20] ./~/debug/debug.js 4.1 kB {0} [built]
[21] ./~/ms/index.js 2.33 kB {0} [built]
[24] ./~/inherits/inherits.js 192 bytes {0} [built]
[25] ./~/inherits/inherits_browser.js 672 bytes {0} [built]
[27] ./~/sockjs-client/lib/transport/driver/websocket.js 51 bytes {0} [built]
[28] ./~/sockjs-client/~/faye-websocket/lib/faye/websocket.js 1.33 kB {0} [built]
[29] ./~/websocket-driver/lib/websocket/driver.js 1.39 kB {0} [built]
[30] ./~/websocket-driver/lib/websocket/driver/base.js 3.47 kB {0} [built]
[31] ./~/websocket-driver/lib/websocket/streams.js 4.91 kB {0} [built]
[33] ./~/websocket-driver/lib/websocket/driver/headers.js 815 bytes {0} [built]
[34] ./~/websocket-driver/lib/websocket/driver/stream_reader.js 1.87 kB {0} [built]
[35] ./~/websocket-driver/lib/websocket/driver/client.js 4.16 kB {0} [built]
[36] ./~/websocket-driver/lib/websocket/http_parser.js 2.5 kB {0} [built]
[37] ./~/websocket-driver/lib/websocket/driver/hybi.js 14.1 kB {0} [built]
[38] ./~/websocket-extensions/lib/websocket_extensions.js 4.86 kB {0} [built]
[39] ./~/websocket-extensions/lib/parser.js 2.84 kB {0} [built]
[40] ./~/websocket-extensions/lib/pipeline/index.js 1.48 kB {0} [built]
[41] ./~/websocket-extensions/lib/pipeline/cell.js 1.42 kB {0} [built]
[42] ./~/websocket-extensions/lib/pipeline/functor.js 1.35 kB {0} [built]
[43] ./~/websocket-extensions/lib/pipeline/ring_buffer.js 1.6 kB {0} [built]
[44] ./~/websocket-extensions/lib/pipeline/pledge.js 779 bytes {0} [built]
[45] ./~/websocket-driver/lib/websocket/driver/hybi/frame.js 373 bytes {0} [built]
[46] ./~/websocket-driver/lib/websocket/driver/hybi/message.js 888 bytes {0} [built]
[47] ./~/websocket-driver/lib/websocket/driver/proxy.js 2.62 kB {0} [built]
[48] ./~/websocket-driver/lib/websocket/driver/server.js 3.09 kB {0} [built]
[49] ./~/websocket-driver/lib/websocket/driver/draft75.js 3.06 kB {0} [built]
[50] ./~/websocket-driver/lib/websocket/driver/draft76.js 2.99 kB {0} [built]
[51] ./~/sockjs-client/~/faye-websocket/lib/faye/websocket/api.js 5.12 kB {0} [built]
[52] ./~/sockjs-client/~/faye-websocket/lib/faye/websocket/api/event_target.js 624 bytes {0} [built]
[53] ./~/sockjs-client/~/faye-websocket/lib/faye/websocket/api/event.js 505 bytes {0} [built]
[54] ./~/sockjs-client/~/faye-websocket/lib/faye/websocket/client.js 2.72 kB {0} [built]
[56] ./~/sockjs-client/~/faye-websocket/lib/faye/eventsource.js 3.76 kB {0} [built]
[57] ./~/sockjs-client/lib/transport/xhr-streaming.js 1.25 kB {0} [built]
[58] ./~/sockjs-client/lib/transport/lib/ajax-based.js 1.31 kB {0} [built]
[59] ./~/sockjs-client/lib/transport/lib/sender-receiver.js 1.15 kB {0} [built]
[60] ./~/sockjs-client/lib/transport/lib/buffered-sender.js 2.3 kB {0} [built]
[61] ./~/sockjs-client/lib/transport/lib/polling.js 1.32 kB {0} [built]
[62] ./~/sockjs-client/lib/transport/receiver/xhr.js 1.58 kB {0} [built]
[63] ./~/sockjs-client/lib/transport/sender/xhr-cors.js 343 bytes {0} [built]
[64] ./~/sockjs-client/lib/transport/driver/xhr.js 1.64 kB {0} [built]
[67] ./~/sockjs-client/lib/transport/sender/xhr-local.js 352 bytes {0} [built]
[68] ./~/sockjs-client/lib/utils/browser.js 560 bytes {0} [built]
[69] ./~/sockjs-client/lib/transport/xdr-streaming.js 984 bytes {0} [built]
[70] ./~/sockjs-client/lib/transport/sender/xdr.js 2.46 kB {0} [built]
[71] ./~/sockjs-client/lib/transport/eventsource.js 766 bytes {0} [built]
[72] ./~/sockjs-client/lib/transport/receiver/eventsource.js 1.58 kB {0} [built]
[73] ./~/eventsource/lib/eventsource.js 8.9 kB {0} [built]
[74] ./~/original/index.js 1.04 kB {0} [built]
[75] ./~/original/~/url-parse/index.js 6.55 kB {0} [built]
[76] ./~/original/~/url-parse/lolcation.js 1.4 kB {0} [built]
[77] ./~/sockjs-client/lib/transport/lib/iframe-wrap.js 981 bytes {0} [built]
[78] ./~/sockjs-client/lib/transport/iframe.js 3.83 kB {0} [built]
[79] ./~/json3/lib/json3.js 43.3 kB {0} [built]
[80] (webpack)/buildin/module.js 251 bytes {0} [built]
[81] (webpack)/buildin/amd-options.js 43 bytes {0} [built]
[82] ./~/sockjs-client/lib/version.js 26 bytes {0} [built]
[83] ./~/sockjs-client/lib/utils/iframe.js 5.06 kB {0} [built]
[84] ./~/sockjs-client/lib/utils/object.js 532 bytes {0} [built]
[85] ./~/sockjs-client/lib/transport/htmlfile.js 710 bytes {0} [built]
[86] ./~/sockjs-client/lib/transport/receiver/htmlfile.js 2.2 kB {0} [built]
[87] ./~/sockjs-client/lib/transport/xhr-polling.js 894 bytes {0} [built]
[88] ./~/sockjs-client/lib/transport/xdr-polling.js 712 bytes {0} [built]
[89] ./~/sockjs-client/lib/transport/jsonp-polling.js 1.02 kB {0} [built]
[90] ./~/sockjs-client/lib/transport/receiver/jsonp.js 5.57 kB {0} [built]
[91] ./~/sockjs-client/lib/transport/sender/jsonp.js 2.46 kB {0} [built]
[92] ./~/sockjs-client/lib/main.js 11.9 kB {0} [built]
[93] ./~/sockjs-client/lib/shims.js 18.2 kB {0} [built]
[94] ./~/sockjs-client/lib/utils/escape.js 2.31 kB {0} [built]
[95] ./~/sockjs-client/lib/utils/transport.js 1.35 kB {0} [built]
[96] ./~/sockjs-client/lib/utils/log.js 450 bytes {0} [built]
[97] ./~/sockjs-client/lib/event/event.js 477 bytes {0} [built]
[98] ./~/sockjs-client/lib/event/eventtarget.js 1.85 kB {0} [built]
[99] ./~/sockjs-client/lib/location.js 177 bytes {0} [built]
[100] ./~/sockjs-client/lib/event/close.js 295 bytes {0} [built]
[101] ./~/sockjs-client/lib/event/trans-message.js 292 bytes {0} [built]
[102] ./~/sockjs-client/lib/info-receiver.js 2.22 kB {0} [built]
[103] ./~/sockjs-client/lib/transport/sender/xhr-fake.js 456 bytes {0} [built]
[104] ./~/sockjs-client/lib/info-iframe.js 1.52 kB {0} [built]
[105] ./~/sockjs-client/lib/info-iframe-receiver.js 791 bytes {0} [built]
[106] ./~/sockjs-client/lib/info-ajax.js 1.03 kB {0} [built]
[107] ./~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {0} [built]
[108] ./~/sockjs-client/lib/facade.js 723 bytes {0} [built]
[109] (webpack)/hot/dev-server.js 1.85 kB {0} [built]
[110] (webpack)/hot/log-apply-result.js 813 bytes {0} [built]
[111] ./app/src/main.js 1.18 kB {0} [built]
[112] ./~/babel-runtime/helpers/extends.js 544 bytes {0} [built]
[113] ./~/babel-runtime/core-js/object/assign.js 94 bytes {0} [built]
[114] ./~/core-js/library/fn/object/assign.js 106 bytes {0} [built]
[115] ./~/core-js/library/modules/es6.object.assign.js 159 bytes {0} [built]
[116] ./~/core-js/library/modules/_export.js 2.31 kB {0} [built]
[117] ./~/core-js/library/modules/_global.js 322 bytes {0} [built]
[118] ./~/core-js/library/modules/_core.js 117 bytes {0} [built]
[119] ./~/core-js/library/modules/_ctx.js 505 bytes {0} [built]
[120] ./~/core-js/library/modules/_a-function.js 120 bytes {0} [built]
[121] ./~/core-js/library/modules/_hide.js 288 bytes {0} [built]
[122] ./~/core-js/library/modules/_object-dp.js 608 bytes {0} [built]
[123] ./~/core-js/library/modules/_an-object.js 149 bytes {0} [built]
[124] ./~/core-js/library/modules/_is-object.js 107 bytes {0} [built]
[125] ./~/core-js/library/modules/_ie8-dom-define.js 192 bytes {0} [built]
[126] ./~/core-js/library/modules/_descriptors.js 177 bytes {0} [built]
[127] ./~/core-js/library/modules/_fails.js 99 bytes {0} [built]
[128] ./~/core-js/library/modules/_dom-create.js 286 bytes {0} [built]
[129] ./~/core-js/library/modules/_to-primitive.js 644 bytes {0} [built]
[130] ./~/core-js/library/modules/_property-desc.js 183 bytes {0} [built]
[131] ./~/core-js/library/modules/_object-assign.js 1.16 kB {0} [built]
[132] ./~/core-js/library/modules/_object-keys.js 225 bytes {0} [built]
[133] ./~/core-js/library/modules/_object-keys-internal.js 546 bytes {0} [built]
[134] ./~/core-js/library/modules/_has.js 117 bytes {0} [built]
[135] ./~/core-js/library/modules/_to-iobject.js 213 bytes {0} [built]
[136] ./~/core-js/library/modules/_iobject.js 236 bytes {0} [built]
[137] ./~/core-js/library/modules/_cof.js 103 bytes {0} [built]
[138] ./~/core-js/library/modules/_defined.js 157 bytes {0} [built]
[139] ./~/core-js/library/modules/_array-includes.js 788 bytes {0} [built]
[140] ./~/core-js/library/modules/_to-length.js 217 bytes {0} [built]
[141] ./~/core-js/library/modules/_to-integer.js 158 bytes {0} [built]
[142] ./~/core-js/library/modules/_to-index.js 230 bytes {0} [built]
[143] ./~/core-js/library/modules/_shared-key.js 158 bytes {0} [built]
[144] ./~/core-js/library/modules/_shared.js 198 bytes {0} [built]
[145] ./~/core-js/library/modules/_uid.js 158 bytes {0} [built]
[146] ./~/core-js/library/modules/_enum-bug-keys.js 159 bytes {0} [built]
[147] ./~/core-js/library/modules/_object-gops.js 41 bytes {0} [built]
[148] ./~/core-js/library/modules/_object-pie.js 36 bytes {0} [built]
[149] ./~/core-js/library/modules/_to-object.js 129 bytes {0} [built]
[150] ./app/~/vue/dist/vue.common.js 141 kB {0} [built]
[151] ./app/~/vue-electron/index.js 47 bytes {0} [built]
[152] ./app/~/vue-electron/src/vue-electron.js 103 bytes {0} [built]
[154] ./app/~/vue-resource/dist/vue-resource.common.js 34.5 kB {0} [built]
[155] ./app/~/vue-router/dist/vue-router.js 43.9 kB {0} [built]
[156] ./app/src/App.vue 1.64 kB {0} [built]
[157] ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-1!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/App.vue 1.35 kB {0} [built]
[158] ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-1!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/App.vue 1.42 kB {0} [built]
[159] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[160] ./~/css-loader?sourceMap!./~/ace-css/css/ace.min.css 64.6 kB {0} [built]
[161] ./~/css-loader?sourceMap!./~/animate.css/animate.min.css 123 kB {0} [built]
[162] ./~/vue-style-loader/addStyles.js 6.24 kB {0} [built]
[163] ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./app/src/App.vue 331 bytes {0} [built]
[164] ./app/src/vuex/store.js 1.03 kB {0} [built]
[165] ./app/~/vuex/dist/vuex.js 14.2 kB {0} [built]
[166] ./app/src/vuex/actions.js 812 bytes {0} [built]
[167] ./app/src/vuex/mutation-types.js 255 bytes {0} [built]
[168] ./app/src/vuex/getters.js 182 bytes {0} [built]
[169] ./app/src/vuex/modules/index.js 319 bytes {0} [built]
[170] ./app/src/vuex/modules nonrecursive \.js$ 193 bytes {0} [built]
[171] ./app/src/vuex/modules/counters.js 1.07 kB {0} [optional] [built]
[172] ./~/babel-runtime/helpers/defineProperty.js 540 bytes {0} [built]
[173] ./~/babel-runtime/core-js/object/define-property.js 103 bytes {0} [built]
[174] ./~/core-js/library/fn/object/define-property.js 213 bytes {0} [built]
[175] ./~/core-js/library/modules/es6.object.define-property.js 214 bytes {0} [built]
[176] ./~/vue-loader/lib/template-compiler.js?id=data-v-1!./~/vue-loader/lib/selector.js?type=template&index=0!./app/src/App.vue 331 bytes {0} [built]
[177] ./~/vue-loader/~/vue-hot-reload-api/index.js 3.07 kB {0} [built]
[178] ./app/src/routes.js 226 bytes {0} [built]
[179] ./app/src/components/LandingPageView.vue 1.74 kB {0} [built]
[180] ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-2&scoped=true!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/components/LandingPageView.vue 1.45 kB {0} [built]
[181] ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-2&scoped=true!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/components/LandingPageView.vue 6.4 kB {0} [built]
[182] ./~/css-loader?sourceMap!./~/nouislider/distribute/nouislider.css 13.5 kB {0} [built]
[183] ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./app/src/components/LandingPageView.vue 2.18 kB {0} [built]
[184] ./app/src/components/LandingPageView/CurrentPage.vue 1.6 kB {0} [built]
[185] ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-5&scoped=true!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/components/LandingPageView/CurrentPage.vue 1.47 kB {0} [built]
[186] ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-5&scoped=true!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/components/LandingPageView/CurrentPage.vue 1.09 kB {0} [built]
[187] ./~/vue-loader/lib/template-compiler.js?id=data-v-5!./~/vue-loader/lib/selector.js?type=template&index=0!./app/src/components/LandingPageView/CurrentPage.vue 396 bytes {0} [built]
[188] ./app/src/components/LandingPageView/Links.vue 1.59 kB {0} [built]
[189] ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-4&scoped=true!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/components/LandingPageView/Links.vue 1.45 kB {0} [built]
[190] ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-4&scoped=true!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/components/LandingPageView/Links.vue 1.19 kB {0} [built]
[191] ./~/vue-loader/lib/template-compiler.js?id=data-v-4!./~/vue-loader/lib/selector.js?type=template&index=0!./app/src/components/LandingPageView/Links.vue 663 bytes {0} [built]
[192] ./app/src/components/LandingPageView/Versions.vue 1.5 kB {0} [built]
[193] ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./app/src/components/LandingPageView/Versions.vue 409 bytes {0} [built]
[195] ./~/vue-loader/lib/template-compiler.js?id=data-v-3!./~/vue-loader/lib/selector.js?type=template&index=0!./app/src/components/LandingPageView/Versions.vue 400 bytes {0} [built]
[196] ./~/nouislider/distribute/nouislider.js 57.6 kB {0} [built]
[197] ./~/vue-loader/lib/template-compiler.js?id=data-v-2!./~/vue-loader/lib/selector.js?type=template&index=0!./app/src/components/LandingPageView.vue 4.96 kB {0} [built]
+ 13 hidden modules
Child html-webpack-plugin for "index.html":
chunk    {0} index.html 535 kB [rendered]
[0] ./~/html-webpack-plugin/lib/loader.js!./app/index.ejs 637 bytes {0} [built]
[1] ./~/lodash/lodash.js 534 kB {0} [built]
[2] (webpack)/buildin/module.js 251 bytes {0} [built]

webpack  webpack: bundle is now VALID.

Starting electron...

electron

electron  Attempted to load

electron  extension "devtron" that has already been loaded.

electron  mainWindow opened
```

**Comment by SimulatedGREG** [comment] 2016-10-06 16:57
I can't seem to determine where the issue is coming from, as it could be an internal problem with [`electron-devtools-intaller`](https://github.com/MarshallOfSound/electron-devtools-installer). Could you leave you development environment details and I'll take a look later today when I get a chance?

  * Node version:
  * NPM version:
  * Operating System:

**Comment by wdmtech** [comment] 2016-10-06 17:04
Sure thing:

`node -v` : v6.6.0  
`npm -v` : 3.10.3  
`os` : Windows 7 Professional (SP1)

I've also tried on:

`node -v` : v5.10.1  
`npm -v` : 3.10.8

Thanks @SimulatedGREG :smile:

**Comment by wdmtech** [comment] 2016-10-07 12:29
Not sure if it's this - but I did `npm i` in `./app` and now I seem to have Vue devtools!

**Comment by SimulatedGREG** [comment] 2016-10-07 18:21
Glad to hear that! Still not sure what the problem is though. Going to label this a dependency issue. Related to [vue-devtools #62](https://github.com/vuejs/vue-devtools/issues/62).

**Closed by SimulatedGREG** 2016-10-07 18:21 UTC
Labels: bug, needs-info
